@startuml
title Hotel_Record

entity login_accounts {
    + **id : bigint(20) [PK] **
    --
    name : varchar(255)
    * email : varchar(255) [UK]
    password : varchar(255)
    created_at : timestamp
    updated_at : timestamp
}

entity contents {
    + **id : bigint(20) [PK] **
    --
    # login_account_id : bigint(20) [FK]
    # category_id : bigint(20) [FK]
    # image_id : bigint(20) [FK]
    have_visited : tinyint(1)
    name : varchar(255)
    check_in_date : datetime
    check_out_date : datetime
    memo : text
    created_at : timestamp
    updated_at : timestamp
}

entity categories {
    + **id : bigint(20) [PK] **
    --
    # login_account_id : bigint(20) [FK]
    name : varchar(255)
    created_at : timestamp
    updated_at : timestamp
}

entity images {
    + **id : bigint(20) [PK] **
    --
    # contents_id : bigint(20) [FK]
    file_name : varchar(255)
    file_path : varchar(255)
    created_at : timestamp
    updated_at : timestamp
}

login_accounts ||--o{ contents
login_accounts ||--{ categories
contents ||--|| categories
contents ||--o{ images

@enduml