// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwc8XPlNv8m-qQR5lmjTV1EsaOonF1VyE',
    appId: '1:911611774065:web:cd03d3e6b146939f62c7d0',
    messagingSenderId: '911611774065',
    projectId: 'book-list-sample-bb29c',
    authDomain: 'book-list-sample-bb29c.firebaseapp.com',
    storageBucket: 'book-list-sample-bb29c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx0dZa-ipP7UdR-b5mbW7THELlYVYU3t4',
    appId: '1:911611774065:android:9d4f67fd75cb5bd462c7d0',
    messagingSenderId: '911611774065',
    projectId: 'book-list-sample-bb29c',
    storageBucket: 'book-list-sample-bb29c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtIq_ZU5Ur70Qmoh761LAwUETqFy8Xv1Q',
    appId: '1:911611774065:ios:ef12a02acdd6fd6062c7d0',
    messagingSenderId: '911611774065',
    projectId: 'book-list-sample-bb29c',
    storageBucket: 'book-list-sample-bb29c.appspot.com',
    iosClientId: '911611774065-26gh1d0mgdroi2jubu0ne9h1sjoi9829.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtIq_ZU5Ur70Qmoh761LAwUETqFy8Xv1Q',
    appId: '1:911611774065:ios:ef12a02acdd6fd6062c7d0',
    messagingSenderId: '911611774065',
    projectId: 'book-list-sample-bb29c',
    storageBucket: 'book-list-sample-bb29c.appspot.com',
    iosClientId: '911611774065-26gh1d0mgdroi2jubu0ne9h1sjoi9829.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
